[project]
name = "auto-hunter-ai"
version = "0.1.0"
dependencies = [
    "streamlit",
    "langfuse",
    "google-genai",
    "google-generativeai",
    "openai",
    "selenium",
    "webdriver-manager",
    "python-dotenv",
    "beautifulsoup4",
    "PyPDF2",
    "pandas"
]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"
